name: DevOps Capstone Deployment

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Build Java application
        run: mvn -f java-app/pom.xml package -DskipTests

      - name: Build Lambda application
        run: mvn -f lambda/pom.xml clean package -DskipTests


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2


      - name: Terraform Init
        working-directory: terraform
        run: terraform init


      - name: Create Lambda deployment bucket
        working-directory: terraform
        run: terraform apply -target=aws_s3_bucket.lambda_deployment -auto-approve


      - name: Upload Lambda JAR to S3
        working-directory: terraform
        run: |
          BUCKET_NAME=$(terraform state show aws_s3_bucket.lambda_deployment | grep '^bucket ' | awk '{print $3}' | tr -d '"')
          aws s3 cp ../lambda/target/yearbook-lambda-1.0.0.jar s3://$BUCKET_NAME/yearbook-lambda-1.0.0.jar


      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Configure SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > /tmp/cohort8-key.pem
          chmod 600 /tmp/cohort8-key.pem


      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible rsync


      - name: Create Ansible inventory
        run: |
          EC2_IP=$(terraform -chdir=terraform output -raw ec2_public_ip)
          echo "[webserver]" > ansible/inventory.ini
          echo "devops-server ansible_host=$EC2_IP ansible_user=ubuntu ansible_ssh_private_key_file=/tmp/cohort8-key.pem" >> ansible/inventory.ini


      - name: Configure EC2 with Ansible
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml